cluster.name: 'elk-tls-cluster'
network.host: '0.0.0.0'
http.host: 0.0.0.0

xpack.license.self_generated.type: trial

xpack.security.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.authc.api_key.enabled: true

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: ${CONFIG_DIR}/elasticsearch.key
xpack.security.transport.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: ${CONFIG_DIR}/elasticsearch.key
xpack.security.http.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
